kind = "web"
previewPath = "/"
title = "Craftofy"
version = "1.0.0"
id = "artifacts/craftofy"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21715

[services.development]
run = "pnpm --filter @workspace/craftofy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/craftofy", "run", "build" ]
publicDir = "artifacts/craftofy/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21715"
BASE_PATH = "/"
